### PR TITLE
Allow to collect items into associative array using `Get.get_all()`

### PR DESCRIPTION
**Pull request by dekameron**
It'll be good to have possibility to receive an associative array from get_all();

### CODE REVIEW

**Comment by gerryd** [comment]
Hello Anatol,

Thank you for your contribution.

Could you maybe elaborate on the use-case you are trying to address?

**Comment by dekameron** [comment]
Hi!
Sometimes it's good for me to have the related objects indexed by `id` in example.
So I guess it will be useful for other developers.

This is mostly a "syntax sugar".

**Comment by gerryd** [comment]
I somewhat see what you are trying to do, however I still don't see when you would need to do this. Could you give an example of a situation where you would need the array indexed by ID?

One issue with your current proposal is that you could potentially not get all results anymore when calling `get_all()`. For example, if you supply "firstname" as the column to use as the index, and there's more than one person named "Anatol" in your table, you'd only get one of them (and if you're using MySQL, not even always the same, depending on the state of your database).

**Comment by dekameron** [comment]
OK. In example I have a table with some options (just id, name, and maybe some other fields), in my case this is `media_type` table.
Also I have `organization` table. Every organization have some active `media_types`  related via `organization_media_type` table that contains: `organization_id`, `media_type_id`, `is_default`.

So, when I'm saving organization media types (List of ids) it's good to have ids of all currenlty related media types (`array_keys`) and also check existing related type using `array_key_exists`.

Yes, I can potentially not get all results using non unique field, but, I guess, every developer knows what he did. We can't protect all the developers from bad solutions

**Pull request closed without merging**
